// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3005' | (string & {});
};

export type PostApiTimeLogsData = {
    body?: {
        employeeId: number;
        timestamp: string;
        photoUrl?: string;
        deviceId: string;
        deviceInfo?: {
            [key: string]: unknown;
        };
        source: 'MACHINE' | 'APP' | 'WEB';
    };
    path?: never;
    query?: never;
    url: '/api/time-logs';
};

export type PostApiTimeLogsResponses = {
    200: unknown;
};

export type PostApiProcessLogsData = {
    body?: {
        limit?: number;
    };
    path?: never;
    query?: never;
    url: '/api/process-logs';
};

export type PostApiProcessLogsResponses = {
    200: unknown;
};

export type PostApiTimesheetsInitData = {
    body?: {
        employeeId: number;
        groupIds?: Array<number>;
        startDate: string;
        endDate: string;
        lifecycle?: {
            joinedDate?: string;
            terminatedDate?: string;
        };
    };
    path?: never;
    query?: never;
    url: '/api/timesheets/init';
};

export type PostApiTimesheetsInitResponses = {
    200: unknown;
};

export type PostApiTimesheetsPublishData = {
    body?: {
        employeeId: number;
        startDate: string;
        endDate: string;
    };
    path?: never;
    query?: never;
    url: '/api/timesheets/publish';
};

export type PostApiTimesheetsPublishResponses = {
    200: unknown;
};

export type GetApiTimesheetsData = {
    body?: never;
    path?: never;
    query: {
        employeeId: string;
        startDate: string;
        endDate: string;
        includeDrafts?: string;
    };
    url: '/api/timesheets';
};

export type GetApiTimesheetsResponses = {
    200: unknown;
};

export type GetApiTimesheetsLatestData = {
    body?: never;
    path?: never;
    query: {
        employeeId: string;
    };
    url: '/api/timesheets/latest';
};

export type GetApiTimesheetsLatestResponses = {
    200: unknown;
};

export type PostApiConfigTimeSlotsData = {
    body?: {
        name: string;
        sessions: Array<{
            startTime: string;
            endTime: string;
            isOvernight?: boolean;
        }>;
        breakRules?: Array<{
            startTime: string;
            endTime: string;
            isPaid?: boolean;
            type?: 'FIXED' | 'DYNAMIC';
            triggerAfterMinutes?: number | null;
        }>;
    };
    path?: never;
    query?: never;
    url: '/api/config/time-slots';
};

export type PostApiConfigTimeSlotsResponses = {
    200: unknown;
};

export type PostApiConfigWorkCyclesData = {
    body?: {
        name: string;
        type: 'WEEKLY' | 'BI_WEEKLY' | 'CUSTOM';
        cycleLength: number;
        cycleDays: Array<{
            dayNumber: number;
            timeSlotId: number | null;
        }>;
    };
    path?: never;
    query?: never;
    url: '/api/config/work-cycles';
};

export type PostApiConfigWorkCyclesResponses = {
    200: unknown;
};

export type PostApiConfigAssignmentsData = {
    body?: {
        groupId?: number;
        employeeId?: number;
        workCycleId: number;
        effectiveFrom: string;
        effectiveTo?: string | null;
        timezone?: string;
        earlyStartTolerance?: number;
        lateStartTolerance?: number;
        earlyEndTolerance?: number;
        lateEndTolerance?: number;
        priority?: number;
    };
    path?: never;
    query?: never;
    url: '/api/config/assignments';
};

export type PostApiConfigAssignmentsResponses = {
    200: unknown;
};

export type PostApiConfigEmployeeGroupsData = {
    body?: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/config/employee-groups';
};

export type PostApiConfigEmployeeGroupsResponses = {
    200: unknown;
};

export type GetApiConfigResolveAssignmentData = {
    body?: never;
    path?: never;
    query: {
        employeeId?: string;
        groupId: string;
        date: string;
    };
    url: '/api/config/resolve-assignment';
};

export type GetApiConfigResolveAssignmentResponses = {
    200: unknown;
};

export type GetApiConfigShiftCollisionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config/shift-collision';
};

export type GetApiConfigShiftCollisionResponses = {
    /**
     * Shift collision configuration
     */
    200: {
        companyId: number;
        defaultResolution: 'BLOCK' | 'SPLIT' | 'PRIORITY' | 'PROMPT' | 'FIRST_IN';
        exceptions?: Array<{
            shiftTypeA: string;
            shiftTypeB: string;
            resolution: 'BLOCK' | 'SPLIT' | 'PRIORITY' | 'PROMPT' | 'FIRST_IN';
        }>;
        id: string;
    };
};

export type GetApiConfigShiftCollisionResponse = GetApiConfigShiftCollisionResponses[keyof GetApiConfigShiftCollisionResponses];

export type PutApiConfigShiftCollisionData = {
    body?: {
        companyId: number;
        defaultResolution: 'BLOCK' | 'SPLIT' | 'PRIORITY' | 'PROMPT' | 'FIRST_IN';
        exceptions?: Array<{
            shiftTypeA: string;
            shiftTypeB: string;
            resolution: 'BLOCK' | 'SPLIT' | 'PRIORITY' | 'PROMPT' | 'FIRST_IN';
        }>;
    };
    path?: never;
    query?: never;
    url: '/api/config/shift-collision';
};

export type PutApiConfigShiftCollisionResponses = {
    /**
     * Updated configuration
     */
    200: {
        companyId: number;
        defaultResolution: 'BLOCK' | 'SPLIT' | 'PRIORITY' | 'PROMPT' | 'FIRST_IN';
        exceptions?: Array<{
            shiftTypeA: string;
            shiftTypeB: string;
            resolution: 'BLOCK' | 'SPLIT' | 'PRIORITY' | 'PROMPT' | 'FIRST_IN';
        }>;
        id: string;
    };
};

export type PutApiConfigShiftCollisionResponse = PutApiConfigShiftCollisionResponses[keyof PutApiConfigShiftCollisionResponses];

export type PostApiConfigShiftCollisionExceptionsData = {
    body?: {
        shiftTypeA: string;
        shiftTypeB: string;
        resolution: 'BLOCK' | 'SPLIT' | 'PRIORITY' | 'PROMPT' | 'FIRST_IN';
    };
    path?: never;
    query?: never;
    url: '/api/config/shift-collision/exceptions';
};

export type PostApiConfigShiftCollisionExceptionsResponses = {
    /**
     * Updated configuration with new exception
     */
    200: {
        companyId: number;
        defaultResolution: 'BLOCK' | 'SPLIT' | 'PRIORITY' | 'PROMPT' | 'FIRST_IN';
        exceptions?: Array<{
            shiftTypeA: string;
            shiftTypeB: string;
            resolution: 'BLOCK' | 'SPLIT' | 'PRIORITY' | 'PROMPT' | 'FIRST_IN';
        }>;
        id: string;
    };
};

export type PostApiConfigShiftCollisionExceptionsResponse = PostApiConfigShiftCollisionExceptionsResponses[keyof PostApiConfigShiftCollisionExceptionsResponses];

export type DeleteApiConfigShiftCollisionExceptionsIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/config/shift-collision/exceptions/{id}';
};

export type DeleteApiConfigShiftCollisionExceptionsIdResponses = {
    /**
     * Updated configuration
     */
    200: {
        companyId: number;
        defaultResolution: 'BLOCK' | 'SPLIT' | 'PRIORITY' | 'PROMPT' | 'FIRST_IN';
        exceptions?: Array<{
            shiftTypeA: string;
            shiftTypeB: string;
            resolution: 'BLOCK' | 'SPLIT' | 'PRIORITY' | 'PROMPT' | 'FIRST_IN';
        }>;
        id: string;
    };
};

export type DeleteApiConfigShiftCollisionExceptionsIdResponse = DeleteApiConfigShiftCollisionExceptionsIdResponses[keyof DeleteApiConfigShiftCollisionExceptionsIdResponses];

export type GetApiPendingAttributionsData = {
    body?: never;
    path?: never;
    query?: {
        employeeId?: string;
        date?: string;
        status?: 'PENDING' | 'RESOLVED';
    };
    url: '/api/pending-attributions';
};

export type GetApiPendingAttributionsResponses = {
    200: unknown;
};

export type PostApiPendingAttributionsIdResolveData = {
    body?: {
        resolvedShiftId: string;
        resolvedBy: number;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/pending-attributions/{id}/resolve';
};

export type PostApiPendingAttributionsIdResolveResponses = {
    200: unknown;
};

export type GetApiOvertimeSchedulesData = {
    body?: never;
    path?: never;
    query: {
        groupId: number;
        startDate: string;
        endDate: string;
    };
    url: '/api/overtime/schedules';
};

export type GetApiOvertimeSchedulesResponses = {
    200: unknown;
};

export type PostApiOvertimeSchedulesData = {
    body?: {
        groupId: number;
        startDate: string;
        endDate: string;
        startTime: string;
        endTime: string;
        breaks?: Array<{
            startTime: string;
            endTime: string;
            isPaid: boolean;
            type?: 'FIXED' | 'DYNAMIC';
            triggerAfterMinutes?: number;
        }>;
        description?: string;
        createdBy: number;
    };
    path?: never;
    query?: never;
    url: '/api/overtime/schedules';
};

export type PostApiOvertimeSchedulesResponses = {
    200: unknown;
};

export type GetApiOvertimeRequestsData = {
    body?: never;
    path?: never;
    query?: {
        employeeId?: number;
        status?: 'PENDING' | 'APPROVED' | 'REJECTED';
        startDate?: string;
        endDate?: string;
    };
    url: '/api/overtime/requests';
};

export type GetApiOvertimeRequestsResponses = {
    200: unknown;
};

export type PostApiOvertimeRequestsData = {
    body?: {
        employeeId: number;
        date: string;
        startTime: string;
        endTime: string;
        reason?: string;
        scheduleId?: string;
    };
    path?: never;
    query?: never;
    url: '/api/overtime/requests';
};

export type PostApiOvertimeRequestsResponses = {
    200: unknown;
};

export type PostApiOvertimeRequestsIdApproveData = {
    body?: {
        reviewerId: number;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/overtime/requests/{id}/approve';
};

export type PostApiOvertimeRequestsIdApproveResponses = {
    200: unknown;
};

export type PostApiOvertimeRequestsIdRejectData = {
    body?: {
        reviewerId: number;
        note?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/overtime/requests/{id}/reject';
};

export type PostApiOvertimeRequestsIdRejectResponses = {
    200: unknown;
};

export type PostApiCompanyCompanyIdTimePeriodsData = {
    body?: {
        companyId: number;
        name: string;
        startTime: string;
        endTime: string;
        displayOrder?: number;
        isActive?: boolean;
    };
    path: {
        companyId: string;
    };
    query?: never;
    url: '/api/company/{companyId}/time-periods';
};

export type PostApiCompanyCompanyIdTimePeriodsResponses = {
    200: unknown;
};

export type PutApiCompanyCompanyIdRoundingPoliciesData = {
    body?: {
        companyId: number;
        context: 'WORK_HOURS' | 'OVERTIME' | 'LATE_IN' | 'EARLY_OUT';
        mode: 'NONE' | 'UP' | 'DOWN' | 'NEAREST' | 'TRUNCATE';
        intervalMinutes: 1 | 5 | 15 | 30 | 60;
        minimumThreshold?: number;
        isActive?: boolean;
    };
    path: {
        companyId: string;
    };
    query?: never;
    url: '/api/company/{companyId}/rounding-policies';
};

export type PutApiCompanyCompanyIdRoundingPoliciesResponses = {
    200: unknown;
};

export type GetApiEmployeesEmployeeIdShiftOverridesData = {
    body?: never;
    path: {
        employeeId: string;
    };
    query?: {
        date?: string;
        startDate?: string;
        endDate?: string;
    };
    url: '/api/employees/{employeeId}/shift-overrides';
};

export type GetApiEmployeesEmployeeIdShiftOverridesResponses = {
    /**
     * List of shift overrides
     */
    200: Array<{
        employeeId?: number;
        date: string;
        shiftId: number;
        mode: 'REPLACE' | 'ADD';
        reason?: string;
        priority?: number;
        projectCode?: string;
        createdBy: number;
    }>;
};

export type GetApiEmployeesEmployeeIdShiftOverridesResponse = GetApiEmployeesEmployeeIdShiftOverridesResponses[keyof GetApiEmployeesEmployeeIdShiftOverridesResponses];

export type PostApiEmployeesEmployeeIdShiftOverridesData = {
    body?: {
        employeeId?: number;
        date: string;
        shiftId: number;
        mode: 'REPLACE' | 'ADD';
        reason?: string;
        priority?: number;
        projectCode?: string;
        createdBy: number;
    };
    path: {
        employeeId: string;
    };
    query?: never;
    url: '/api/employees/{employeeId}/shift-overrides';
};

export type PostApiEmployeesEmployeeIdShiftOverridesErrors = {
    /**
     * Conflict (e.g. Overlap detected and blocked)
     */
    409: unknown;
};

export type PostApiEmployeesEmployeeIdShiftOverridesResponses = {
    /**
     * Created shift override
     */
    201: {
        employeeId?: number;
        date: string;
        shiftId: number;
        mode: 'REPLACE' | 'ADD';
        reason?: string;
        priority?: number;
        projectCode?: string;
        createdBy: number;
        id: string;
        collisionId: string | null;
    };
};

export type PostApiEmployeesEmployeeIdShiftOverridesResponse = PostApiEmployeesEmployeeIdShiftOverridesResponses[keyof PostApiEmployeesEmployeeIdShiftOverridesResponses];

export type DeleteApiEmployeesEmployeeIdShiftOverridesIdData = {
    body?: never;
    path: {
        employeeId: string;
        id: string;
    };
    query?: never;
    url: '/api/employees/{employeeId}/shift-overrides/{id}';
};

export type DeleteApiEmployeesEmployeeIdShiftOverridesIdResponses = {
    /**
     * Shift override deleted
     */
    204: void;
};

export type DeleteApiEmployeesEmployeeIdShiftOverridesIdResponse = DeleteApiEmployeesEmployeeIdShiftOverridesIdResponses[keyof DeleteApiEmployeesEmployeeIdShiftOverridesIdResponses];

export type GetApiEmployeesEmployeeIdEffectiveShiftsData = {
    body?: never;
    path: {
        employeeId: string;
    };
    query: {
        date: string;
    };
    url: '/api/employees/{employeeId}/effective-shifts';
};

export type GetApiEmployeesEmployeeIdEffectiveShiftsResponses = {
    /**
     * List of effective shifts
     */
    200: unknown;
};

export type GetApiPoliciesData = {
    body?: never;
    path?: never;
    query: {
        companyId: string;
        type?: 'WORK_WINDOW' | 'BREAK_DURATION' | 'SATURDAY_BONUS' | 'OVERTIME_THRESHOLD' | 'TOLERANCE';
    };
    url: '/api/policies';
};

export type GetApiPoliciesResponses = {
    /**
     * List of policies
     */
    200: unknown;
};

export type PostApiPoliciesData = {
    body?: {
        companyId: number;
        name: string;
        policyType: 'WORK_WINDOW' | 'BREAK_DURATION' | 'SATURDAY_BONUS' | 'OVERTIME_THRESHOLD' | 'TOLERANCE';
        config: {
            startTime: string;
            endTime: string;
            flexMode?: boolean;
            expectedHours?: number;
            maxDailyHours?: number;
        } | {
            durationMinutes: number;
            startTime?: string;
            endTime?: string;
            isPaid?: boolean;
        } | {
            enabled: boolean;
            bonusMinutes: number;
        } | {
            dailyThresholdMinutes: number;
            weeklyThresholdMinutes?: number;
        } | {
            lateInMinutes: number;
            earlyOutMinutes: number;
        };
        description?: string;
    };
    path?: never;
    query?: never;
    url: '/api/policies';
};

export type PostApiPoliciesErrors = {
    /**
     * Invalid input
     */
    400: unknown;
};

export type PostApiPoliciesResponses = {
    /**
     * Policy created successfully
     */
    201: unknown;
};

export type DeleteApiPoliciesIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/policies/{id}';
};

export type DeleteApiPoliciesIdResponses = {
    /**
     * Policy deleted
     */
    204: void;
};

export type DeleteApiPoliciesIdResponse = DeleteApiPoliciesIdResponses[keyof DeleteApiPoliciesIdResponses];

export type GetApiPoliciesIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/policies/{id}';
};

export type GetApiPoliciesIdErrors = {
    /**
     * Policy not found
     */
    404: unknown;
};

export type GetApiPoliciesIdResponses = {
    /**
     * Policy details
     */
    200: unknown;
};

export type PutApiPoliciesIdData = {
    body?: {
        name?: string;
        config?: {
            startTime: string;
            endTime: string;
            flexMode?: boolean;
            expectedHours?: number;
            maxDailyHours?: number;
        } | {
            durationMinutes: number;
            startTime?: string;
            endTime?: string;
            isPaid?: boolean;
        } | {
            enabled: boolean;
            bonusMinutes: number;
        } | {
            dailyThresholdMinutes: number;
            weeklyThresholdMinutes?: number;
        } | {
            lateInMinutes: number;
            earlyOutMinutes: number;
        };
        description?: string;
        isActive?: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/policies/{id}';
};

export type PutApiPoliciesIdErrors = {
    /**
     * Policy not found
     */
    404: unknown;
};

export type PutApiPoliciesIdResponses = {
    /**
     * Policy updated
     */
    200: unknown;
};

export type GetApiPolicyGroupsData = {
    body?: never;
    path?: never;
    query: {
        companyId: string;
    };
    url: '/api/policy-groups';
};

export type GetApiPolicyGroupsResponses = {
    /**
     * List of groups
     */
    200: unknown;
};

export type PostApiPolicyGroupsData = {
    body?: {
        companyId: number;
        name: string;
        code: string;
        description?: string;
    };
    path?: never;
    query?: never;
    url: '/api/policy-groups';
};

export type PostApiPolicyGroupsResponses = {
    /**
     * Group created
     */
    201: unknown;
};

export type PostApiPolicyGroupsIdMembersData = {
    body?: {
        employeeId: number;
        effectiveFrom: string;
        effectiveTo?: string | null;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/policy-groups/{id}/members';
};

export type PostApiPolicyGroupsIdMembersResponses = {
    /**
     * Member added
     */
    201: unknown;
};

export type DeleteApiPolicyGroupsIdMembersEmployeeIdData = {
    body?: never;
    path: {
        id: string;
        employeeId: string;
    };
    query?: never;
    url: '/api/policy-groups/{id}/members/{employeeId}';
};

export type DeleteApiPolicyGroupsIdMembersEmployeeIdResponses = {
    /**
     * Member removed
     */
    204: void;
};

export type DeleteApiPolicyGroupsIdMembersEmployeeIdResponse = DeleteApiPolicyGroupsIdMembersEmployeeIdResponses[keyof DeleteApiPolicyGroupsIdMembersEmployeeIdResponses];

export type GetApiPolicyAssignmentsData = {
    body?: never;
    path?: never;
    query?: {
        companyId?: string;
        groupId?: string;
        employeeId?: string;
    };
    url: '/api/policy-assignments';
};

export type GetApiPolicyAssignmentsResponses = {
    /**
     * List of assignments
     */
    200: unknown;
};

export type PostApiPolicyAssignmentsData = {
    body?: {
        policyId: string;
        companyId?: number;
        groupId?: number;
        employeeId?: number;
        effectiveFrom: string;
        effectiveTo?: string | null;
        priority?: number;
        createdBy: number;
    };
    path?: never;
    query?: never;
    url: '/api/policy-assignments';
};

export type PostApiPolicyAssignmentsResponses = {
    /**
     * Assignment created
     */
    201: unknown;
};

export type DeleteApiPolicyAssignmentsIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/policy-assignments/{id}';
};

export type DeleteApiPolicyAssignmentsIdResponses = {
    /**
     * Assignment deleted
     */
    204: void;
};

export type DeleteApiPolicyAssignmentsIdResponse = DeleteApiPolicyAssignmentsIdResponses[keyof DeleteApiPolicyAssignmentsIdResponses];

export type GetApiEmployeesIdEffectivePoliciesData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        date: string;
        companyId: string;
    };
    url: '/api/employees/{id}/effective-policies';
};

export type GetApiEmployeesIdEffectivePoliciesResponses = {
    /**
     * Effective policies
     */
    200: unknown;
};
